ubda/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, send_file, abort
from flask_login import login_required, current_user
from .models import *
from . import db
import time
from datetime import datetime
from werkzeug.security import generate_password_hash
from .device_server import send_reset_cmd, send_sync_cmd, send_ota_cmd, online_devices
import io
import json

views = Blueprint('views', __name__)


@views.route('/')
@login_required
def home():
    if current_user.role != 'admin':    
        return redirect(url_for('views.user_home'))
    return render_template("home.html", user=current_user)


@views.route('/user')
@login_required
def user_home():
    al = Access_level.query.filter_by(id=current_user.access_level).first()
    aps = al.access_points
    return render_template("user_home.html", user=current_user, aps=aps)


@views.route('/devices')
@login_required
def devices():
    if current_user.role != 'admin':    
        flash('Restricted area', category='error')
        return redirect(url_for('views.user_home'))
    devs = Device.query.all()
    now = int(time.time()) 
    return render_template("devices.html", 
                           user = current_user, 
                           devs = devs, 
                           now = now, 
                           online_devices = online_devices)


@views.route('/edit_device/<string:id>', methods=['GET', 'POST'])
@login_required
def edit_device(id):
    if current_user.role != 'admin':    
        flash('Restricted area', category='error')
        return redirect(url_for('views.user_home'))
    device = Device.query.filter_by(id=id).first()
    if not device :
        flash(f'No device with id:{id}', category='error')
        return redirect(url_for('views.devices'))
    if request.method == 'POST':
        name = request.form.get('Name')
        config = request.form.get('Config')
        try:
            j = json.loads(config)
        except:
            j = None
        if j is not None: #
            device.name = name
            device.config = config
            db.session.add(device)
            db.session.commit()
            flash('Device updated', category='success')
        else:
            flash('Wrong format, config must be json', category='error')
        return redirect(url_for('views.devices'))
    return render_template("edit_device.html", user = current_user, device = device)


@views.route('/delete_device/<string:id>', methods=['GET', 'POST'])
@login_required
def delete_device(id):
    if current_user.role != 'admin':    
        flash('Restricted area', category='error')
        return redirect(url_for('views.user_home'))
    device = Device.query.filter_by(id=id).first()
    if not device :
        flash(f'No device with id:{id}', category='error')
        return redirect(url_for('views.devices'))
    if request.method == 'POST':
        send_reset_cmd(device)##########################
        db.session.delete(device)
        db.session.commit()
        flash('Device deleted', category='success')
        return redirect(url_for('views.devices'))
    return render_template("delete_device.html", user = current_user, device=device)


@views.route('/get_cards/<string:id>')
def send_cards(id):
    device = Device.query.filter_by(mac=id).first()
    if not device :
        abort(404)
    buff = io.BytesIO()
    access_point = Access_point.query.filter_by(id=device.access_point).first()
    for access_level in access_point.access_levels:
        #access_level = Access_level.query.filter_by(id=access_level_id).first() 
        for user in access_level.users:
            c=user.card_number
            if c:
                buff.write(user.card_number.to_bytes(4,'big'))
    buff.seek(0)
    return send_file(buff, download_name='cards')
    

@views.route('/get_config/<string:id>')
def send_config(id):
    device = Device.query.filter_by(mac=id).first()
    if not device :
        abort(404)
    buf = io.BytesIO()
    if device.config is None:
        buf.write('''{"aps":[
            {"ssid":"shvancki","password":"11111111"},
            {"ssid":"10 e block guest","password":""},
            {"ssid":"GREAN_WIFI","password":"wifipass"},
            {"ssid":"OCH Lobby","password":"och2020!"},
            {"ssid":"MyLePort","password":"myleport"}
            ],
        "server_address":"wss://ubda.ge/ws",
        "ota_server_address":"https://static.ubda.ge",
        "config_host":"http://ubda.ge",
        "unlock_time" : 1000,
        "ota_filenames":[
        {"file":"boot.py"},
        {"file":"main.py"},
        {"file":"ws.py"},
        {"file":"wiegand.py"},
        {"file":"ota.py"},
        {"file":"config.json"}
        ],
        "model":"fumfli_c3"''').encode()
    else:
        buf.write(device.config.encode())
    buf.seek(0)
    return send_file(buf, download_name='conf.json')

@views.route('/update_fw/<string:id>', methods=['GET', 'POST'])
@login_required
def update_fw(id):
    if current_user.role != 'admin':    
        flash('Restricted area', category='error')
        return redirect(url_for('views.user_home'))
    device = Device.query.filter_by(id=id).first()
    if not device :
        flash(f'No device with id:{id}', category='error')
        return redirect(url_for('views.devices'))
    if request.method == 'POST':
        ###send reset command
        send_ota_cmd(device)
        ###
        flash('OTA request sent', category='success')
        return redirect(url_for('views.devices'))
    return render_template("ota.html", user = current_user, device=device)

@views.route('/reset_device/<string:id>', methods=['GET', 'POST'])
@login_required
def reset_device(id):
    if current_user.role != 'admin':    
        flash('Restricted area', category='error')
        return redirect(url_for('views.user_home'))
    device = Device.query.filter_by(id=id).first()
    if not device :
        flash(f'No device with id:{id}', category='error')
        return redirect(url_for('views.devices'))
    if request.method == 'POST':
        ###send reset command
        send_reset_cmd(device)
        ###
        flash('Reset request sent', category='success')
        return redirect(url_for('views.devices'))
    return render_template("reset_device.html", user = current_user, device=device)

@views.route('/sync_device/<string:id>', methods=['GET', 'POST'])
@login_required
def sync_device(id):
    if current_user.role != 'admin':    
        flash('Restricted area', category='error')
        return redirect(url_for('views.user_home'))
    device = Device.query.filter_by(id=id).first()
    if not device :
        flash(f'No device with id:{id}', category='error')
        return redirect(url_for('views.devices'))
    if request.method == 'POST':
        
        send_sync_cmd(device)
        
        flash('Sync request sent', category='success')
        return redirect(url_for('views.devices'))
    return render_template("sync_device.html", user = current_user, device=device)


@views.route('/device_log/<string:id>')
@login_required
def device_log(id):
    if current_user.role != 'admin':    
        flash('Restricted area', category='error')
        return redirect(url_for('views.user_home'))
    device = Device.query.filter_by(id=id).first()
    if not device:
        flash(f'No device with id:{id}', category='error')
        return redirect(url_for('views.devices'))
    else:
        return render_template("device_log.html", 
                                device= device)


@views.route('/outputs')
@login_required
def outputs():
    if current_user.role != 'admin':    
        flash('Restricted area', category='error')
        return redirect(url_for('views.user_home'))
    devs = Device.query.all()
    return render_template("outputs.html", current_user = current_user, devs = devs)


@views.route('/edit_output/<string:id>', methods=['GET', 'POST'])
@login_required
def edit_output(id):
    if current_user.role != 'admin':    
        flash('Restricted area', category='error')
        return redirect(url_for('views.user_home'))
    output = Output.query.filter_by(id=id).first()
    if not output :
        flash(f'No output with id:{id}', category='error')
        return redirect(url_for('views.outputs'))
    if request.method == 'POST':
        name = request.form.get('Name')
        output.name = name
        db.session.add(output)
        db.session.commit()
        flash('Output information updated', category='success')
        return redirect(url_for('views.outputs'))
    return render_template("edit_output.html", user = current_user, output = output)




#access levels
#******************************
@views.route('/access_levels')
@login_required
def access_levels():
    if current_user.role != 'admin':    
        flash('Restricted area', category='error')
        return redirect(url_for('views.user_home'))
    accessLevels = Access_level.query.all() 
    return render_template("access_levels.html", user = current_user, access_levels = accessLevels)

@views.route('/add_access_level', methods=['GET', 'POST'])
@login_required
def add_access_level():
    if current_user.role != 'admin':    
        flash('Restricted area', category='error')
        return redirect(url_for('views.user_home'))
    access_points = Access_point.query.all()
    outputs = Output.query.all()
    if request.method == 'POST':
        description = request.form.get('description')
        name = request.form.get('name')    
        access_level = Access_level.query.filter_by(name=name).first()
        if access_level:
            flash(f'Access level with name:"{name}" already exists', category='error')
        elif len(name) < 2:
            flash('Too short name', category='error')
        else:
            new_access_level = Access_level(description = description, name = name)
            for access_point in access_points:
                if request.form.get(access_point.name):

ubda/templates/add_person.html
{% extends "base.html" %} {% block title %}new person{% endblock %} 
{% block content %}
<form method="POST">
    <h3 align="center">new person</h3>

    <div class="form-group">
      <label for="firstName">First Name</label>
      <input
        type="text"
        class="form-control"
        id="firstName"
        name="firstName"
        placeholder="Enter first name"
      />
    </div>
    <div class="form-group">
        <label for="lastName">Last Name</label>
        <input
          type="text"
          class="form-control"
          id="lastName"
          name="lastName"
          placeholder="Enter last name"
        />
      </div>
      <div class="form-group">
        <label for="email">email</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
    <div class="form-group">
      <label for="pin">pin</label>
      <input
        type="text"
        class="form-control"
        id="pin"
        name="pin"
        placeholder="Enter pin"
      />
    </div>
    <div class="form-group">
      <label for="card_number">Card number</label>
      <input
        type="number"
        class="form-control"
        id="card_number"
        name="card_number"
        placeholder="Enter card number"
      />
    </div>
    <div class="form-group">
      <label for="accessLevel">Access level</label>
      <select
        class="form-control"
        id="access_level"
        name="access_level"
        placeholder="Access level">
        {% for a in access_levels %}
        <option value={{a.id}}>{{a.name}}</option>
        {% endfor %}
      </select>
    </div>
    <div class="form-group">
      <label for="valid_thru">Valid thru</label>
      <input
        type="date"
        class="form-control"
        id="valid_thru"
        name="valid_thru"
        placeholder="Enter date"
      />
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

{% endblock %}

ubda/templates/delete_access_level.html
{% extends "base.html" %} {% block title %}Delete{% endblock %} 
{% block nav %}
{% endblock %}
{% block content %}
<h3>delete access level "{{ access_level.name }}" ?<h3>
    <form method="POST">
        <button type="submit" class="btn btn-primary">Yes</button>
    </form>
    <a href = "{{ url_for('views.access_levels') }}">
        <button type="submit" class="btn btn-primary">Cancel</button>
    </a>  
{% endblock %}

ubda/templates/device_log.html
{% extends "base.html" %} {% block title %}Device log{% endblock %} 
{% block content %}

<h3>{{device.name}} ({{device.mac}}) -  log</h3>
<br>
<style>
  table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }
  
  td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
  }
  
  tr:nth-child(even) {
    background-color: #dddddd;
  }
  </style>
<table style="width:100%">
  <tr>
    <th>Content</th>
    <th>Date time</th>
  </tr>
  {% for entry in device.log %}
  <tr>
    <td>{{ entry.content }}</td>
    <td>{{ entry.date_time }}</td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

ubda/templates/devices.html
{% extends "base.html" %} {% block title %}Devices{% endblock %} 
{% block nav %} 
<a class="nav-item nav-link" id="newDevice" href="/devices">New device</a>
{% endblock %}
{% block content %}

<style>
  table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }
  
  td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
  }
  
  tr:nth-child(even) {
    background-color: #dddddd;
  }
  </style>
<table style="width:100%">
  <tr>
    <th>Name</th>
    <th>MAC</th>
    <th>Model</th>
    <th>Last seen</th>
    <th>SV</th>
    <th> </th>
    <th> </th>
    <th> </th>
    <th> </th>
    <th> </th>
    <th> </th>
  </tr>
  {% for dev in devs %}
  <tr>
    <td
    {% if dev.id not in online_devices %}
    bgcolor="red"
    {% elif online_devices[dev.id]==0 %}
    bgcolor="red"
    {% endif %}>
    {{ dev.name }}</td>
    <td>{{ dev.mac }}</td>
    <td>{{ dev.model }}</td>
    <td>{{ now - dev.last_seen }} seconds ago</td>
    <td>{{ dev.sv }}</td>
    <td><a href="{{ url_for('views.device_log', id = dev.id) }}">Log</a></td>
    <td><a href="{{ url_for('views.delete_device', id = dev.id) }}">Delete</a></td>
    <td><a href="{{ url_for('views.edit_device', id = dev.id) }}">Edit</a></td>
    <td><a href="{{ url_for('views.reset_device', id = dev.id) }}">Reset</a></td>
    <td><a href="{{ url_for('views.sync_device', id = dev.id) }}">Sync</a></td>
    <td><a href="{{ url_for('views.update_fw', id = dev.id) }}">OTA</a></td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

ubda/templates/edit_access_level.html
{% extends "base.html" %} {% block title %}Edit Access level{% endblock %} 
{% block content %}
<form method="POST">
    <h3 align="center">Edit Access level</h3>
    <div class="form-group">
        <label for="name">Name</label>
        <input
          type="text"
          class="form-control"
          id="name"
          name="name"
          placeholder="Enter name"
          value = "{{ access_level.name }}"
        />
      </div>
    <div class="form-group">
      <label for="description">Description</label>
      <input
        type="text"
        class="form-control"
        id="description"
        name="description"
        placeholder="Enter description"
        value = "{{ access_level.description }}"
      />
    </div>
    {% for a in access_points %}
    <br>
    Access point {{a.name}}: 
    <label for="{{a.name}}">{{a.name}} ({{a.id}}) </label> 
    <input type="checkbox" id="{{a.name}}" name="{{a.name}}" value="{{a.name}}"
    {% if a in access_level.access_points %} checked {% endif %}>
    <br>
    {% for d in a.devices %}
    Device {{d.name}} ({{d.mac}}):
    {% for o in d.outputs %}
    |<label for="{{o.id}}">{{o.name}}</label> 
    <input type="checkbox" id="{{o.id}}" name="{{o.id}}" value="{{o.id}}"
    {% if o in access_level.outputs %} checked {% endif %}> |
    {% endfor %}
    <br>
    {% endfor %}
    <br><hr>
    {% endfor %}
    <br>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

ubda/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %}
{% block nav %}
<a class="nav-item nav-link" id="change_password" href="/change_password">Change password</a>
{% endblock %}
{% block content%}
<h3>Logged in as {{ user.user_name }}</h3>

{% endblock %}

ubda/templates/message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Refresh" content="5; url='{{ url }}'" />
    <title>Message</title>
</head>
<body>
    {% with messages = get_flashed_messages() %} 
    {% if messages %} 
    {% for message in messages %} 
    <h1> 
        {{ message }}
    </h1>
    {% endfor %} {% endif %} {% endwith %}
</body>
</html>

ubda/templates/ota.html
{% extends "base.html" %} {% block title %}OTA{% endblock %} 
{% block nav %}
{% endblock %}
{% block content %}
<h3>Update firmware "{{ device.name }}({{ device.mac }})" ?<h3>
    <form method="POST">
        <button type="submit" class="btn btn-primary">Yes</button>
    </form>
    <a href = "{{ url_for('views.devices') }}">
        <button type="submit" class="btn btn-primary">Cancel</button>
    </a>  
{% endblock %}

ubda/templates/reset_device.html
{% extends "base.html" %} {% block title %}Reset{% endblock %} 
{% block nav %}
{% endblock %}
{% block content %}
<h3>Reset device "{{ device.name }}({{ device.mac }})" ?<h3>
    <form method="POST">
        <button type="submit" class="btn btn-primary">Yes</button>
    </form>
    <a href = "{{ url_for('views.devices') }}">
        <button type="submit" class="btn btn-primary">Cancel</button>
    </a>  
{% endblock %}

ubda/templates/sign_up.html
{% extends "base.html" %} {% block title %}New User{% endblock %} {% block
content %}
<form method="POST">
  <h3 align="center">New User</h3>
  <div class="form-group">
    <label for="useraName">User Name</label>
    <input
      type="text"
      class="form-control"
      id="userName"
      name="userName"
      placeholder="Enter user name"
    />
  </div>
  <div class="form-group">
    <label for="firstName">First Name</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Enter first name"
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

ubda/templates/sync_device.html
{% extends "base.html" %} {% block title %}Sync{% endblock %} 
{% block nav %}
{% endblock %}
{% block content %}
<h3>Sync device "{{ device.name }}({{ device.mac }})" ?<h3>
    <form method="POST">
        <button type="submit" class="btn btn-primary">Yes</button>
    </form>
    <a href = "{{ url_for('views.devices') }}">
        <button type="submit" class="btn btn-primary">Cancel</button>
    </a>  
{% endblock %}

ubda/templates/user_access_log.html
{% extends "base.html" %} {% block title %}User access log{% endblock %} 
{% block content %}

<h3>{{ user.user_name }} - access log</h3>
<br>
<style>
  table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }
  
  td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
  }
  
  tr:nth-child(even) {
    background-color: #dddddd;
  }
  </style>
<table style="width:100%">
  <tr>
    <th>Access point</th>
    <th>Content</th>
    <th>Date time</th>
  </tr>
  {% for entry in user.access_log %}
  <tr>
    <td>{{ entry.access_point }} - "{{ ap_names[entry.access_point] }}"</td>
    <td>{{ entry.content }}</td>
    <td>{{ entry.date_time }}</td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

ubda/templates/user_base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="/static/bootstrap-4.0.0/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="/static/fontawesome/css/fontawesome.min.css"
    />

    <title>UBDA - {% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if current_user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          {% block nav %} {% endblock %}    
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>

    <script
      src="/static/jquery-3.7.1.slim.min.js"
    ></script>

    <script
      src="/static/popper/popper.min.js"
    ></script>

    <script
      src="/static/bootstrap-4.0.0/js/bootstrap.min.js"
    ></script>
  </body>
</html>

ubda/templates/users.html
{% extends "base.html" %} {% block title %}Users{% endblock %} 
{% block nav %}
<a class="nav-item nav-link" id="addPerson" href="{{ url_for('user_views.new_user') }}">New user</a>
<a class="nav-item nav-link" id="exportUsers" href="{{ url_for('user_views.export_users') }}">Export users</a>
<a class="nav-item nav-link" id="importUsers" href="{{ url_for('user_views.import_users') }}">Import users</a>
{% endblock %}
{% block content %}

<style>
  table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }
  
  td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
  }
  
  tr:nth-child(even) {
    background-color: #dddddd;
  }
  </style>
<table style="width:100%">
  <tr>
    <th>User name</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Card number</th>
    <th>Access level</th>
    <th>Role</th>
    <th> </th>
    <th> </th>
    <th> </th>
  </tr>
  {% for usr in users %}
  <tr>
    <td>{{ usr.user_name }}</td>
    <td>{{ usr.first_name }}</td>
    <td>{{ usr.last_name }}</td>
    <td>{{ usr.card_number }}</td>
    <td>{{ usr.access_level }} - "{{ access_level_names[usr.access_level] }}"</td>
    <td>{{ usr.role }}</td>
    <td><a href="{{ url_for('user_views.user_access_log', id = usr.id) }}">Log</a></td>
    <td><a href="{{ url_for('user_views.edit_user', id = usr.id) }}">Edit</a></td>
    <td><a href="{{ url_for('user_views.delete_user', id = usr.id) }}">Delete</a></td>
  </tr>
  {% endfor %}
</table>
{% endblock %}